### ISSUE TITLE
Suggestion for chapters in this repo

### ISSUE THREAD

**Issue by Ks89** [antoniolg/Kotlin-for-Android-Developers#4]
Hi Antonio,
why are you using commits and not branches to specify different chapters? XD It's only an idea.

**Comment by antoniolg** [comment]
I had it that way at the beginning, but it was much more difficult to maintain. This book (and repository) has been updated on any new Kotlin release, and that implied modifying all the branches affected by language modifications. If there was a change in one of the first commits, I had to redo the main branch and all the secondary branches, which was a painful job and didn't provide any big advantages.

You can checkout individual commits and have the same result, and it's really easy from Android Studio "version control" panel.

**Comment by shekibobo** [comment]
You could also tag the commits for each relevant chapter to make them easier to check out from local source control:

```
git checkout <commit>
git tag chapter-01
git push --tags
```

**Comment by antoniolg** [comment]
If you think it's useful, that would be easy. But all the commits are relevant, because there's one commit per chapter, so not sure it would add much simplicity.

**Comment by shekibobo** [comment]
it's just one less step if I want to skip between chapter code, rather than looking up the commit and checking it out, I could just `checkout chapter-10`. Predictable. However, if you rewrite the whole repo when there are updates, you'd need to redo the tags on the new commits and force push them. So that's an extra step on your part. Just a suggestion. Thanks for the great introduction!
